### ISSUE TITLE
notify-desktop kills dunst and xfce4-notification-daemon

### ISSUE THREAD

**Issue by lharding** [nowrep/notify-desktop#1]
Receiving a notification message from `notify-desktop` causes both dunst and xfce4-notification-daemon to segfault. It seems to happen regardless of arguments to notify-desktop.

Thanks for trying to raise the water level for non-DE users! :+1:

**Comment by nowrep** [comment]
If it crashes the daemon, then the bug is in the daemon. There is nothing in code that could make it happen, it just calls one DBus method.

It works fine with Plasma 5.
